apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner-2
  labels:
    app: github-runner-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner-2
  template:
    metadata:
      labels:
        app: github-runner-2
    spec:
      containers:
      - name: github-runner-2
        image: gcr.io/dev1-designpat-playground-e09c/github-runner:1.4.3-removeGroup
        volumeMounts:
        - name: gcp-sa-token
          mountPath: "/home/runner/security" # This is gcloud SA
          readOnly: true
        env:
        - name: RUNNER_REPOSITORY_URL
          value: https://github.com/OLB-PoC/designpat-environment
        - name: RUNNER_NAME
          value: Test-Prod-Runner
        - name: REPO
          value: designpat-environment
        - name: ORGANIZATION
          value: OLB-PoC
        - name: ENVIRONMENT
          value: prod
        - name: GITHUB_TOKEN # stored separately in a Kubernetes Secret
          valueFrom:
            secretKeyRef:
              name: github-token
              key: github-token
        - name: ACCESS_TOKEN # stored separately in a Kubernetes Secret
          valueFrom:
            secretKeyRef:
              name: github-token
              key: github-token
      volumes:
      - name: gcp-sa-token
        secret:
          secretName: gcp-sa-token
          items:
          - key: key.json
            path: key.json
      - name: github-token
        secret:
          secretName: github-token
