apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: gcr.io/devtestdb-287311/github-runner:v10-docker
        env:
        - name: ORGANIZATION
          value: org-example-db
        - name: ACCESS_TOKEN # should be stored separately in a Kubernetes Secret
          value: 219c5f178e7d070f557faf9586873721505b63e4