apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: gcr.io/devtestdb-287311/github-runner:v10-gcloud
        volumeMounts:
        - name: gcp-sa-token
          mountPath: "/home/runner/security" # This is gcloud SA
          readOnly: true
        env:
        - name: ORGANIZATION
          value: org-example-db
        - name: ACCESS_TOKEN # stored separately in a Kubernetes Secret
          valueFrom:
            secretKeyRef:
              name: github-token
              key: access-token
      volumes:
      - name: gcp-sa-token
        secret:
          secretName: gcp-sa-token
          items:
          - key: token.json
            path: token.json
      - name: github-token
        secret:
          secretName: github-token
